const GET_TEST_DATA = 'GET_TEST_DATA';
const GET_TEST_DATA_PENDING = `${GET_TEST_DATA}_PENDING`;
const GET_TEST_DATA_REJECTED = `${GET_TEST_DATA}_REJECTED`;
const GET_TEST_DATA_FULFILLED = `${GET_TEST_DATA}_FULFILLED`;

const ActionTypes = {
    GET_TEST_DATA,
    GET_TEST_DATA_REJECTED,
    GET_TEST_DATA_FULFILLED,
    GET_TEST_DATA_PENDING
};

export default ActionTypes;
