const GET_EVERYTHING_BY_TOPIC = 'GET_EVERYTHING_BY_TOPIC';
const GET_HEADLINES_BY_COUNTRY = 'GET_HEADLINES_BY_COUNTRY';
const GET_EVERYTHING_BY_TOPIC_PENDING = `${GET_EVERYTHING_BY_TOPIC}_PENDING`;
const GET_EVERYTHING_BY_TOPIC_FULFILLED = `${GET_EVERYTHING_BY_TOPIC}_FULFILLED`;
const GET_EVERYTHING_BY_TOPIC_REJECTED = `${GET_EVERYTHING_BY_TOPIC}_REJECTED`;
const GET_HEADLINES_BY_COUNTRY_PENDING = 'GET_HEADLINES_BY_COUNTRY_PENDING';
const GET_HEADLINES_BY_COUNTRY_FULFILLED = 'GET_HEADLINES_BY_COUNTRY_FULFILLED';
const GET_HEADLINES_BY_COUNTRY_REJECTED = 'GET_HEADLINES_BY_COUNTRY_REJECTED';

const NewsActionTypes = {
    GET_EVERYTHING_BY_TOPIC,
    GET_HEADLINES_BY_COUNTRY,
    GET_EVERYTHING_BY_TOPIC_PENDING,
    GET_EVERYTHING_BY_TOPIC_FULFILLED,
    GET_EVERYTHING_BY_TOPIC_REJECTED,
    GET_HEADLINES_BY_COUNTRY_PENDING,
    GET_HEADLINES_BY_COUNTRY_FULFILLED,
    GET_HEADLINES_BY_COUNTRY_REJECTED
};

export default NewsActionTypes;
